add_newline = false 

format = """ $directory$character""" 

right_format = """$git_branch\
$git_state\
$git_status\
$cmd_duration"""

[character] 
success_symbol = "[➜](bold blue) [:](bold blue)" 
error_symbol = "[➜](bold blue) [✗](bold red)" 

[cmd_duration] 
min_time = 500 
style = "bold yellow"
format = "took [$duration]($style) "

[directory] 
style = "green" 
read_only = " 🔒"
truncation_symbol = "../" 
truncate_to_repo = false 

[git_branch] 
format = "[$branch(:$remote_branch)]($style)[*](bright-black) " 

[git_status] 
modified = "~"
