[env]
ENV = "xterm-256color"

[general]
import = [
    "./palette.toml"
]

[cursor.style]
shape = "block"
blinking = "Never"

[mouse]
hide_when_typing = true

[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Regular"

[font.italic]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
padding = { x = 0, y = 0 }
startup_mode = "Fullscreen"
